# Generated by Django 6.0 on 2025-12-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.event')),
                ('occurrence', models.CharField(max_length=255)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
            ],
            bases=('tracker.event',),
        ),
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.event')),
                ('reason', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('medication', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tracker.event',),
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.event')),
                ('occurrence', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tracker.event',),
        ),
    ]
